name: Build and Release Clicker

on:
  push:
    branches: [master]  # Trigger on pushes to the main branch

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # Use a suitable runner for .NET 6

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish
        run: dotnet publish -p:PublishProfile=FolderProfile

      - name: Get short SHA
        run: |
          short_sha=$(echo ${GITHUB_SHA} | cut -c -7)
          echo "SHORT_SHA=$short_sha" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.SHORT_SHA }}
          name: Release ${{ env.SHORT_SHA }}
          draft: false
          prerelease: false
          files: ./SpencerAutoClicker/Output/SpencerAutoClicker.exe
