name: Build and Release Clicker

on:
  push:
    branches: [master]  # Trigger on pushes to the main branch

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # Use a suitable runner for .NET 6

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish
        run: dotnet publish -p:PublishProfile=FolderProfile

      - name: Get short SHA
        run: |
          short_sha=$(echo ${GITHUB_SHA} | cut -c -7)

      - name: Create GitHub release
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.short_sha }}
          name: Release ${{ env.short_sha }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              name: 'SpencerAutoClicker.exe',
              data: fs.readFileSync('./SpencerAutoClicker/Output/SpencerAutoClicker.exe'),
              content_type: 'application/octet-stream'
            })
